// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJQX7C6mKs_yj1SBezh1kjZgzTwVFm4Kg',
    appId: '1:576873708867:web:bc739f392629145e3283f6',
    messagingSenderId: '576873708867',
    projectId: 'whispr-c0782',
    authDomain: 'whispr-c0782.firebaseapp.com',
    storageBucket: 'whispr-c0782.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV_r0fwYWpWKRq43ggUYY_mQRpwH5GmIY',
    appId: '1:576873708867:android:96d4237edccdd50d3283f6',
    messagingSenderId: '576873708867',
    projectId: 'whispr-c0782',
    storageBucket: 'whispr-c0782.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVmvZ52rnY4Ysmbr6GWfw1YeWhgrtokUo',
    appId: '1:576873708867:ios:42bcd20be4ce55733283f6',
    messagingSenderId: '576873708867',
    projectId: 'whispr-c0782',
    storageBucket: 'whispr-c0782.appspot.com',
    iosBundleId: 'com.example.whispr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVmvZ52rnY4Ysmbr6GWfw1YeWhgrtokUo',
    appId: '1:576873708867:ios:7ad2923f611fdbbd3283f6',
    messagingSenderId: '576873708867',
    projectId: 'whispr-c0782',
    storageBucket: 'whispr-c0782.appspot.com',
    iosBundleId: 'com.example.whispr.RunnerTests',
  );
}
